# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: Deploy application

# on:
#   push:
#     branches: [ master ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: appleboy/ssh-action@master
#       - name: Deploy NodeJS app
#         with:
#           host: ${{secrets.SSH_HOST}}
#           username: ${{ secrets.SSH_USERNAME }}
#           password: ${{ secrets.SSH_PASSWORD }}
#           script: |
#             cd /var/www/html/ # navigate into the folder
#             rm -R forum_backend
#             git clone https://github.com/zacharygevans/forum_backend forum_backend # clone the repo into the 'app' folder
#             cd forum_backend # navigate into the repo
#             npm install # install dependencies 
#             pm2 start server.js # start as a background service.